csi-jetson:
  default: true
  image_arm64: ghcr.io/viam-modules/csi-camera/viam-cpp-base-jetson:0.0.6
  minimum_date: 2023-10-26T20:00:00.0Z
  update_interval: 168h0m0s
  user: testbot
  group: testbot
  persistent: true

csi-pi:
  image_arm64: ghcr.io/viam-modules/csi-camera/viam-cpp-base-pi:0.0.6
  minimum_date: 2023-10-26T20:00:00.0Z
  update_interval: 168h0m0s
  user: testbot
  group: testbot
  persistent: true
